run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      Main:
        files:
          - "!$test"
          - cmd/calendar/**
        allow:
          - $gostd
          - github.com/cheggaaa/pb/v3
          - github.com/spf13/pflag
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/cmd/calendar/commands
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify
          - github.com/google/uuid
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/...
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/domain
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/domain/...
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/domain/entity
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/domain/entity/...
      Infrastructure:
        files:
          - "github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/infrastructure/..."
        allow:
          - $gostd
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/infrastructure/...
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/application/...
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/domain/...
          - github.com/cheggaaa/pb/v3
          - github.com/spf13/pflag
      Application:
        files:
          - "github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/application/..."
        allow:
          - $gostd
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/application/...
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/domain/...
      Domain:
        files:
          - "github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/domain/..."
        allow:
          - $gostd
          - github.com/gkarman/otus_go_home_work/hw12_13_14_15_calendar/internal/domain/...
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
