version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: calendar
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - calendar_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  calendar_pgdata:
