storage:
  type: "memory" # или "sql"
  host: "localhost"
  port: 5432
  db: "calendar"
  user: "user"
  password: "pass"

logger:
  level: "INFO"
  pathToHttpLog: "logs/http.log"

server:
  host: "localhost"
  port: 8080

serverGrpc:
  host: "localhost"
  port: 50051